version: "3"
services:

  localcnsl:
    image: invoicing:localinvoicing
    working_dir: /code
    container_name: localinvoicing
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command:
      - tail
      - -f
      - /dev/null
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge