# Generated by Django 4.2.2 on 2023-09-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("invoice_number", models.UUIDField(null=True, unique=True)),
                ("customer_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=0, null=True)),
                ("unit_price", models.FloatField(default=0, null=True)),
                ("price", models.FloatField(default=0, null=True)),
                (
                    "invoice_num",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.invoice",
                        to_field="invoice_number",
                    ),
                ),
            ],
        ),
    ]
