name: Commit Message Check
on:
  push:
    branches:
      - main  # Adjust to your repository's main branch name

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check Commit Messages
        run: |
          # Define the regex pattern for commit message format
          pattern="^NNG-[0-9]+-.+"

          # Loop through the commits in the push
          for commit in $(git log --format=%s ${{ github.event.before }}..${{ github.sha }}); do
            if ! [[ "$commit" =~ $pattern ]]; then
              echo "error: Commit message format is invalid: $commit"
              exit 1
            fi
          done
